name: Snapshot build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setting nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: install dependencies and build
      run: |
          yarn install
          yarn build
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NEXUS_AUTH_TOKEN }}

    - uses: rlespinasse/github-slug-action@master
    - name: build and publish docker
      run: |
          echo docker build
